### ISSUE TITLE
Master ticket wording within the "Planet Ownership" screen is confusing

### ISSUE THREAD

**Issue by loganallenc** [urbit/bridge#401] opened 2020-02-26 21:37 UTC
Here's an example:

https://twitter.com/realDanKras/status/1232779887196459016?s=20

It's very unclear to these people that the "master ticket" they are being asked to secure is in fact their private key.

**Comment by Fang-** [comment] 2020-02-26 21:43
Is this a dupe of #391?

**Comment by loganallenc** [comment] 2020-02-26 22:34
Yes. Please @jyng save us

**Comment by Fang-** [comment] 2020-02-26 23:13
Closing as duplicate.

**Closed by Fang-** 2020-02-26 23:13 UTC
