### ISSUE TITLE
Error Report: pattern[name] is not a function

### ISSUE THREAD

**Issue by shrugs** [urbit/bridge#392] opened 2020-02-07 17:50 UTC
#  Context

After performing a personal breach on `~bosnyt-raddux`, i waited at the completion screen for a while. eventually i pressed the back button, which threw this error.

peeking at the code it probably references a line near [here](https://github.com/urbit/bridge/blob/f08b3ccc73726ceccc2bea34a45fc7d31dfd1488/src/views/Admin/AdminEditPermissions.js#L90)

reloading bridge and navigating to the networking keys page works as expected

## Error

```
TypeError: pattern[name] is not a function
    at InternalConstructor.matchWith (https://bridge.urbit.org/static/js/2.0afadec5.chunk.js:61028:29)
    at Object.Just (https://bridge.urbit.org/static/js/main.4b7d939e.chunk.js:1610:2465)
    at InternalConstructor.matchWith (https://bridge.urbit.org/static/js/2.0afadec5.chunk.js:61028:29)
    at renderNetworkKeysDetail (https://bridge.urbit.org/static/js/main.4b7d939e.chunk.js:1610:2338)
    at AdminEditPermissions (https://bridge.urbit.org/static/js/main.4b7d939e.chunk.js:1610:3433)
    at dh (https://bridge.urbit.org/static/js/2.0afadec5.chunk.js:159000:7)
    at mj (https://bridge.urbit.org/static/js/2.0afadec5.chunk.js:161692:11)
    at jj (https://bridge.urbit.org/static/js/2.0afadec5.chunk.js:160737:11)
    at Z (https://bridge.urbit.org/static/js/2.0afadec5.chunk.js:160594:15)
    at $i (https://bridge.urbit.org/static/js/2.0afadec5.chunk.js:160453:16)
```

In Bridge version 2.3.3.

**Comment by liam-fitzgerald** [comment] 2020-03-04 23:33
dupe of #403 , logging out from nested routers

**Closed by liam-fitzgerald** 2020-03-04 23:33 UTC
Labels: bug, error handling
