### ISSUE TITLE
Error Report: Minified React error #31

### ISSUE THREAD

**Issue by rmariani** [urbit/bridge#491] opened 2020-07-15 23:04 UTC
I was trying to send two Urbit invites from bridge. I instead got an error.

## Context

I had two emails I was trying to send planet invites to. When I pressed "send" it brought me to the error screen that I was linked to this issue-submission screen from.

I tried to invites send to these same two emails twice. It appears to have used invites, because the "N pending" was incremented by two each time. Maybe just a visual error?

## Error

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bticket%2C%20signedTx%2C%20rawTx%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at mg (https://bridge.urbit.org/static/js/2.458aa4fa.chunk.js:158653:38)
    at z (https://bridge.urbit.org/static/js/2.458aa4fa.chunk.js:158747:7)
    at rb (https://bridge.urbit.org/static/js/2.458aa4fa.chunk.js:158813:13)
    at https://bridge.urbit.org/static/js/2.458aa4fa.chunk.js:158930:23
    at S (https://bridge.urbit.org/static/js/2.458aa4fa.chunk.js:159502:26)
    at mj (https://bridge.urbit.org/static/js/2.458aa4fa.chunk.js:161843:306)
    at jj (https://bridge.urbit.org/static/js/2.458aa4fa.chunk.js:160809:11)
    at Z (https://bridge.urbit.org/static/js/2.458aa4fa.chunk.js:160666:15)
    at $i (https://bridge.urbit.org/static/js/2.458aa4fa.chunk.js:160525:16)
    at https://bridge.urbit.org/static/js/2.458aa4fa.chunk.js:158251:17
```

In Bridge version 2.5.2.

**Comment by Fang-** [comment] 2020-07-16 09:36
Closing as duplicate of #455. As per https://github.com/urbit/bridge/issues/455#issuecomment-637736763 and your observations, it might've been a partial failure that failed to get displayed properly.

> Maybe just a visual error?

If it persists upon page reload, it should be accurately reflecting the chain state.

**Closed by Fang-** 2020-07-16 09:36 UTC
Labels: bug, error handling
