### ISSUE TITLE
Error Report: Please pass numbers as strings or BigNumber objects to avoid precision errors.

### ISSUE THREAD

**Issue by LeePar** [urbit/bridge#316] opened 2019-10-28 03:18 UTC
## Error

```
fromWei@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:140998
kn@https://bridge.urbit.org/static/js/main.d93cb87c.chunk.js:1:123676
Na@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1561481
Go@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1604573
Fo@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1590296
qo@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1587316
Lo@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1585876
yi/<@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1547777
t.unstable_runWithPriority@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1622220
pi@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1547506
yi@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1547723
fi@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1547658
ko@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1584867
Ga@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1564614
e/</<@https://bridge.urbit.org/static/js/main.d93cb87c.chunk.js:1:133377
c/<@https://bridge.urbit.org/static/js/main.d93cb87c.chunk.js:1:23314
u@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1762707
l/a._invoke</<@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1762495
I/</e[t]@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1763129
r@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:2259
o@https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:2461

```

**Comment by LeePar** [comment] 2019-10-28 03:21
Hello. My friend tried to transfer a planet to me. I logged into metamask to accept the transfer and when I try to do so this bridge error appears and the transaction doesn't go through. Halp.

**Comment by Fang-** [comment] 2019-10-28 10:41
Probably duplicate of #306 and #310. Still haven't been able to reproduce...

**Closed** 2019-10-29 17:25 UTC
