### ISSUE TITLE
Error Report: pattern[name] is not a function

### ISSUE THREAD

**Issue by bevk** [urbit/bridge#419] opened 2020-03-14 22:42 UTC
## Context

Just reset keys and downloaded from Arvo.  That seemed successful.  I hit the diagonal arrow in the upper right-hand corner of the "Boot Your Urbit" button and specified that it open in another tab.  It went to a information page at Urbit.  I then pressed the back button on my original page and it showed and error with the option to send to GitHub.  I don't know if this is a significant error. - Thanks

## Error

```
TypeError: pattern[name] is not a function
    at InternalConstructor.matchWith (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:61028:29)
    at Object.Just (https://bridge.urbit.org/static/js/main.21612c58.chunk.js:1744:2465)
    at InternalConstructor.matchWith (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:61028:29)
    at renderNetworkKeysDetail (https://bridge.urbit.org/static/js/main.21612c58.chunk.js:1744:2338)
    at AdminEditPermissions (https://bridge.urbit.org/static/js/main.21612c58.chunk.js:1744:3433)
    at dh (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:159040:7)
    at mj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:161732:11)
    at jj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160777:11)
    at Z (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160634:15)
    at $i (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160493:16)
```

In Bridge version 2.3.5.

**Comment by Fang-** [comment] 2020-06-05 14:27
Closing as duplicate of #332. Thanks for reporting, the context here is helpful!

**Closed by Fang-** 2020-06-05 14:27 UTC
