### ISSUE TITLE
Xpub flow broken for non-master-ticket logins

### ISSUE THREAD

**Issue by critesjosh** [urbit/bridge#586] opened 2021-06-29 23:50 UTC
## Context

Trying to login to the bridge using metamask.

## Error

```
Error: no urbit wallet found
    at Object.Nothing (https://bridge.urbit.org/static/js/main.da5eb4fd.chunk.js:227:521)
    at InternalConstructor.matchWith (https://bridge.urbit.org/static/js/2.10c0856e.chunk.js:36562:29)
    at https://bridge.urbit.org/static/js/main.da5eb4fd.chunk.js:226:55
    at Xpub (https://bridge.urbit.org/static/js/main.da5eb4fd.chunk.js:1259:218)
    at oh (https://bridge.urbit.org/static/js/2.10c0856e.chunk.js:221177:7)
    at Rj (https://bridge.urbit.org/static/js/2.10c0856e.chunk.js:224079:11)
    at Qj (https://bridge.urbit.org/static/js/2.10c0856e.chunk.js:223608:11)
    at Kj (https://bridge.urbit.org/static/js/2.10c0856e.chunk.js:223600:27)
    at yj (https://bridge.urbit.org/static/js/2.10c0856e.chunk.js:223343:7)
    at https://bridge.urbit.org/static/js/2.10c0856e.chunk.js:220378:18
```

In Bridge version 2.8.3.

**Comment by Fang-** [comment] 2021-06-30 14:07
Hmm, I cannot trivially reproduce this. Also a little bit surprised seeing that exact error message in this context.

Can you explain in a bit more detail what steps you take to log in? Also, what browser and version of Metamask are you using?

**Comment by critesjosh** [comment] 2021-06-30 21:26
this happens when i try to login to the bridge using metamask with this url, https://bridge.urbit.org/?kind=xpub. I am directed here when trying to set up my bitcoin wallet on landscape.

**Comment by Fang-** [comment] 2021-06-30 23:11
Oh, I see.

So, the good news is, this issue is valid, and Bridge needs to handle the error in a nicer way.

The bad news is, Bridge only supports getting the Bitcoin xpub from an Urbit/master-ticket style wallet. ie, only when you log in using the default login method. I'm not sure what the intended flow here for non-master-ticket wallets looks like, or whether there's anything we can do in those cases in the first place. cc @pkova or whoever?

For the time being, you may want to bring your own xpub from a Bitcoin wallet outside of Bridge. Alternatively, you could move your planet out of Metamask and onto a master-ticket wallet. (Normal login -> your planet -> ID -> reset keys.)

**Comment by critesjosh** [comment] 2021-07-01 13:22
It looks like the bitcoin wallet doesn't currently support import xpub from ledger, which is what I tried without success. web+urbitgraph://group/~bitbet-bolbel/urbit-community/graph/~darrux-landes/development/170141184505130040924051679604696416256

**Comment by Fang-** [comment] 2022-07-27 14:16
Closing as duplicate of #616.

**Closed by Fang-** 2022-07-27 14:16 UTC
Labels: bug, error handling
