### ISSUE TITLE
Error Report: Please pass numbers as strings or BigNumber objects to avoid precision errors.

### ISSUE THREAD

**Issue by rmariani** [urbit/bridge#373] opened 2020-01-24 21:49 UTC
## Context

I was trying to send 27 planets.

## Error

```
Error: Please pass numbers as strings or BigNumber objects to avoid precision errors.
    at fromWei (https://bridge.urbit.org/static/js/2.a9c86e19.chunk.js:1:69354)
    at Ln (https://bridge.urbit.org/static/js/main.1630d065.chunk.js:1:126319)
    at Na (https://bridge.urbit.org/static/js/2.a9c86e19.chunk.js:1:1556103)
    at Go (https://bridge.urbit.org/static/js/2.a9c86e19.chunk.js:1:1599195)
    at Fo (https://bridge.urbit.org/static/js/2.a9c86e19.chunk.js:1:1584918)
    at qo (https://bridge.urbit.org/static/js/2.a9c86e19.chunk.js:1:1581938)
    at $o (https://bridge.urbit.org/static/js/2.a9c86e19.chunk.js:1:1580498)
    at https://bridge.urbit.org/static/js/2.a9c86e19.chunk.js:1:1542399
    at t.unstable_runWithPriority (https://bridge.urbit.org/static/js/2.a9c86e19.chunk.js:1:1616842)
    at pr (https://bridge.urbit.org/static/js/2.a9c86e19.chunk.js:1:1542128)
```

In Bridge version 2.2.1.

**Comment by rmariani** [comment] 2020-01-24 22:13
It looks like the planet invites were sent

**Comment by rmariani** [comment] 2020-01-24 22:43
Update: The invites were deducted from my planet, yet nobody received them.

**Comment by Fang-** [comment] 2020-01-25 01:32
This is that one darn bug that we thought we fixed like ten times already. What happened here is (probably) that the invites were _created_, but not sent out over email.

**Comment by Fang-** [comment] 2020-01-25 01:33
See also: https://github.com/urbit/bridge/issues?utf8=%E2%9C%93&q=is%3Aissue+please+pass+numbers

**Comment by Fang-** [comment] 2020-07-14 18:35
Closing as duplicate of #410.

**Closed by Fang-** 2020-07-14 18:35 UTC
Labels: bug, error handling
