### ISSUE TITLE
Error Report: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by LRHJO** [urbit/bridge#390] opened 2020-02-06 21:59 UTC
## Context

I pressed the log out button then was notified of this error

## Error

```
TypeError: Cannot read property 'data' of undefined
    at https://bridge.urbit.org/static/js/main.4b7d939e.chunk.js:1194:911
    at Object.useMemo (https://bridge.urbit.org/static/js/2.0afadec5.chunk.js:159329:9)
    at useMemo (https://bridge.urbit.org/static/js/2.0afadec5.chunk.js:155544:16)
    at useRouter (https://bridge.urbit.org/static/js/main.4b7d939e.chunk.js:1194:862)
    at Admin (https://bridge.urbit.org/static/js/main.4b7d939e.chunk.js:1880:1134)
    at dh (https://bridge.urbit.org/static/js/2.0afadec5.chunk.js:159000:7)
    at Jh (https://bridge.urbit.org/static/js/2.0afadec5.chunk.js:159476:7)
    at mj (https://bridge.urbit.org/static/js/2.0afadec5.chunk.js:161749:86)
    at jj (https://bridge.urbit.org/static/js/2.0afadec5.chunk.js:160737:11)
    at Z (https://bridge.urbit.org/static/js/2.0afadec5.chunk.js:160594:15)
```

In Bridge version 2.3.3.

**Comment by liam-fitzgerald** [comment] 2020-03-04 23:37
dupe of #403

**Closed by liam-fitzgerald** 2020-03-04 23:37 UTC
