### ISSUE TITLE
Bridge logins feature a button/icon that doesn't seem to function/work

### ISSUE THREAD

**Issue by urcades** [urbit/bridge#769] opened 2021-11-14 20:10 UTC
These two login options (Master Ticket + Recovery Phrase) appear to feature a gear icon/button that doesn't do anything:

<img width="540" alt="Screen Shot 2021-11-14 at 3 04 40 PM" src="https://user-images.githubusercontent.com/1195363/141696860-2581e33c-2e81-4742-80f5-6e4cb5b6629b.png">

<img width="574" alt="Screen Shot 2021-11-14 at 3 04 20 PM" src="https://user-images.githubusercontent.com/1195363/141696861-827db7a5-9e1c-4022-8bff-e3032f1a1aec.png">

**Comment by jyng** [comment] 2021-11-16 18:03
Duplicate of #665

**Closed** 2022-02-21 14:07 UTC
Labels: L2
