### ISSUE TITLE
Bridge Error on Transaction Failure

### ISSUE THREAD

**Issue by setenforce0** [urbit/bridge#507] opened 2020-07-22 23:50 UTC
## Context

Generating an invite link, transaction failed due to running out of gas

## Error

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bticket%2C%20signedTx%2C%20rawTx%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Qg (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:174063:36)
    at p (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:174153:7)
    at ca (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:174218:37)
    at https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:174342:23
    at R (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:175048:26)
    at Rj (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:177461:306)
    at Qj (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:176905:11)
    at Kj (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:176897:27)
    at yj (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:176640:7)
    at https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:173675:18
```

In Bridge version 2.5.3-1.

**Comment by Fang-** [comment] 2020-07-22 23:58
The error here is duplicate of #455, closing as such. Thank you for filing regardless! Should have a fix for this out later this week.

> transaction failed due to running out of gas

I think we have pretty liberal default limits here, and your transaction (from ~8 minutes ago, right?) has an unusually low gas limit (less than 10% of what we normally set). Did you tweak this manually, maybe? Were you using MetaMask?

**Closed by Fang-** 2020-07-22 23:58 UTC

**Comment by setenforce0** [comment] 2020-07-24 01:53
Just for reference, I manually set gas price and limit in metamask, since I would rather it take longer than usual than pay over 5 dollars in gas just to invite someone. Ended up paying $5.42 in gas anyway :(

**Comment by Fang-** [comment] 2020-07-24 11:01
For future reference, in general, the gas _price_ is fine to tweak*, but the gas _limit_ shouldn't be set to lower. If you do, you risk burning all your gas on a transaction that can't complete.

* of course, Bridge itself has issues around dealing with slower transactions.

If it's any consolation, if your account can't pay for an invite transaction, Bridge will attempt to pay the transaction fees for you. (If you have sufficient ETH in there, it'll happily use that instead, though.)

As for the ridiculous gas prices on Ethereum, this issue is worth keeping an eye on: https://github.com/ethereum/go-ethereum/issues/21350
