### ISSUE TITLE
Error Report: pattern[name] is not a function

### ISSUE THREAD

**Issue by danackerson** [urbit/bridge#469] opened 2020-05-23 08:13 UTC
## Context

I needed to reset my networking keys and checked "Breach continuity" to restart anew. 

The transaction for resetting the network keys completed and I wanted to go back to the download screen.

## Error

```
TypeError: pattern[name] is not a function
    at InternalConstructor.matchWith (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:61032:29)
    at Object.Just (https://bridge.urbit.org/static/js/main.5782ed8d.chunk.js:1882:2492)
    at InternalConstructor.matchWith (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:61032:29)
    at renderNetworkKeysDetail (https://bridge.urbit.org/static/js/main.5782ed8d.chunk.js:1882:2365)
    at AdminEditPermissions (https://bridge.urbit.org/static/js/main.5782ed8d.chunk.js:1882:3460)
    at dh (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:159043:7)
    at mj (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:161735:11)
    at jj (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:160780:11)
    at Z (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:160637:15)
    at $i (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:160496:16)
```

In Bridge version 2.4.2.

**Comment by Fang-** [comment] 2020-06-05 14:27
Closing as duplicate of #332. Thanks for reporting, the context here is helpful!

**Closed by Fang-** 2020-06-05 14:27 UTC
