### ISSUE TITLE
Downloaded master ticket is blank

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#788] opened 2021-11-30 00:29 UTC
In the latest Bridge development version, the Master Ticket PNG contains no ticketing information. The management, spawn, and transfer proxy PNGs all appear to be fine.

I am using Safari on a Mac. This key is for ~difzod on Ropsten.

![difzod-Master Ticket](https://user-images.githubusercontent.com/748181/143963748-904b4a75-9482-470c-9fa5-375eeb39fb82.png)
.

**Comment by nerveharp** [comment] 2021-11-30 00:34
This also plagues Master Ticket shards in Passport downloads.

![zod-Master Ticket Shard 2](https://user-images.githubusercontent.com/748181/143964171-dc1c9298-0725-4e71-855a-f15a8f8af0a6.png)
![zod-Master Ticket Shard 1](https://user-images.githubusercontent.com/748181/143964175-8db9c205-0c0a-43d3-8032-a2ae687df29b.png)
![zod-Master Ticket Shard 3](https://user-images.githubusercontent.com/748181/143964179-5edbbd00-0477-4d8c-8e7b-876e13f23717.png)

**Comment by willbach** [comment] 2021-12-02 20:21
This issue seems to be due to `~zod` on Ropsten only having a single shard in the `shards` list in its wallet. The issue was reproduced on `master` with `~zod`. The console error is:

```
index.js:1 TypeError: Cannot read properties of undefined (reading 'match')
    at Object.shard (index.js:20317)
    at index.js:24499
    at Array.forEach (<anonymous>)
    at index.js:24497
    at Array.map (<anonymous>)
    at generatePng (index.js:24486)
    at index.js:24621
    at Array.map (<anonymous>)
    at PaperRenderer.componentDidMount (index.js:24619)
    ```
    
We'll keep an eye on this when the `roller` branch is merged into `master`

**Closed by willbach** 2021-12-02 20:21 UTC
Labels: bug, L2, functional
