### ISSUE TITLE
Error Report: no urbit wallet found

### ISSUE THREAD

**Issue by phaus** [urbit/bridge#959] opened 2022-02-11 21:04 UTC
## Context

I follow step 2 of the setup of the "Urbit Bitcoin Connector"

<img width="514" alt="Bildschirmfoto 2022-02-11 um 22 02 37" src="https://user-images.githubusercontent.com/346361/153669839-7e822ec1-115b-4899-a8a6-888849ab3d32.png">

I got to the bridge https://bridge.urbit.org/?kind=xpub and connected my matamask plugin

## Error

```
1102/X<@https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:25699
p/p/<@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:366802
1102/G/<@https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:25391
1102/zs<@https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:222299
rs@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3663822
Qo@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3716280
kl@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703456
Sl@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703384
Il@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703245
hl@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3700211
Hi/<@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3649590
t.unstable_runWithPriority@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3727009
zi@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3649367
Hi@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3649537
Qi@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3649470
dl@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3697580
ks@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3669149
101/o/p<@https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:12414
1102/zs</f<@https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:186332
35/O/e/<@https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:257764
c@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3735428
u/a._invoke@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3735217
T/</<@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3735853
r@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:45634
o@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:45838

```

In Bridge version 2.10.5.

**Comment by Fang-** [comment] 2022-02-11 23:49
Bridge doesn't actually support the Bitcoin wallet for non-master ticket logins right now. This obviously needs to be communicated better.

Closing as a duplicate of #586 (and a handful of others). Thanks for filing though!

**Closed by Fang-** 2022-02-11 23:49 UTC
