### ISSUE TITLE
Error Report: no urbit wallet found (also, bridge is spamming a lot of tabs)

### ISSUE THREAD

**Issue by rivpyl-sidfyl** [urbit/bridge#643] opened 2021-10-01 13:17 UTC
I was using the btc wallet app to send some sats to another @p. 
when I got to the bridge sign step, it spammed about 30 tabs for me to sign in - I used metamask to do so -  and then presented me with the error template I'm using now.

```
Error: no urbit wallet found
    at Object.Nothing (https://bridge.urbit.org/static/js/main.2589e507.chunk.js:1:25699)
    at b.matchWith (https://bridge.urbit.org/static/js/2.c64e7708.chunk.js:2:366802)
    at https://bridge.urbit.org/static/js/main.2589e507.chunk.js:1:25391
    at https://bridge.urbit.org/static/js/main.2589e507.chunk.js:1:223304
    at rs (https://bridge.urbit.org/static/js/2.c64e7708.chunk.js:2:3663822)
    at Qo (https://bridge.urbit.org/static/js/2.c64e7708.chunk.js:2:3716280)
    at kl (https://bridge.urbit.org/static/js/2.c64e7708.chunk.js:2:3703454)
    at Sl (https://bridge.urbit.org/static/js/2.c64e7708.chunk.js:2:3703382)
    at Il (https://bridge.urbit.org/static/js/2.c64e7708.chunk.js:2:3703245)
    at hl (https://bridge.urbit.org/static/js/2.c64e7708.chunk.js:2:3700211)
```

In Bridge version 2.10.4.

**Comment by rivpyl-sidfyl** [comment] 2021-10-01 13:51
I should add - I just learned that my xpub is not derived from a master ticket, so I can't sign with bridge anyay.
So the "wallet not found" makes sense.

**Comment by Fang-** [comment] 2021-10-01 14:40
Yes, the "no urbit wallet found" thing is a duplicate of #586. Bridge should be clear that this specific flow is only supported for those logging in with a master ticket.

The tabs thing sounds like an urbit/bitcoin wallet side issue. Bridge does not open any windows/tabs. Closing as such.

**Closed by Fang-** 2021-10-01 14:40 UTC
