### ISSUE TITLE
Invite sending tries to render invite object

### ISSUE THREAD

**Issue by galenwp** [urbit/bridge#466] opened 2020-05-20 13:51 UTC
## Context
Was trying to send an invite. Confirmed, clicked send invite, the progress bar started. It could be that this person has already received their invite. The first time I tried this it took forever and didn't seem to go through — but perhaps it did.

## Error
```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bticket%2C%20signedTx%2C%20rawTx%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at mg (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:158624:38)
    at z (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:158718:7)
    at rb (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:158784:13)
    at https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:158901:23
    at S (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:159473:26)
    at mj (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:161814:306)
    at jj (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:160780:11)
    at Z (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:160637:15)
    at $i (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:160496:16)
    at https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:158222:17
```

> Objects are not valid as a React child (found: object with keys {ticket, signedTx, rawTx}). If you meant to render a collection of children, use an array instead.

In Bridge version 2.4.1.

**Comment by Fang-** [comment] 2020-05-20 15:37
> It could be that this person has already received their invite.

fwiw, if they had already been sent an email, we wouldn't even let you generate/send the (second) invite.

**Comment by Fang-** [comment] 2020-07-14 19:04
_Maybe_ related to #455? I can't quite tell.

**Comment by Fang-** [comment] 2020-07-20 20:21
Having looked at this more, closing as duplicate of #455.

**Closed by Fang-** 2020-07-20 20:21 UTC
Labels: bug, error handling, invite flow
