### ISSUE TITLE
Bridge errors if Metamask transaction rejected during invitation issuance

### ISSUE THREAD

**Issue by sivner-figbus** [urbit/bridge#485] opened 2020-07-07 09:50 UTC
## Context

Issuing an invitation by generating an invite URL

Steps to reproduce:

Log in to Bridge with Metamask
Select a planet with an invite group
Click "add members"
Click "URL"
Click "Generate invite URL"
Wait for the Metamask window to pop up with the gas fee and the reject/confirm choice
Be appalled at the gas fee and click "reject"
Get error.

Maybe looks a little bit like #466 

## Error

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bticket%2C%20signedTx%2C%20rawTx%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at mg (https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158653:38)
    at z (https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158747:7)
    at rb (https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158813:13)
    at https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158930:23
    at S (https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:159502:26)
    at mj (https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:161843:306)
    at jj (https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:160809:11)
    at Z (https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:160666:15)
    at $i (https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:160525:16)
    at https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158251:17
```

In Bridge version 2.5.0.

**Comment by sivner-figbus** [comment] 2020-07-08 06:23
Confirmed same error occurs issuing an invitation, if the metamask transaction popup is rejected, if the invitation is issued as an email rather than a URL.

**Comment by Fang-** [comment] 2020-07-14 19:02
Closing as duplicate of #466 since it's the same error. Thanks for filing regardless!

**Closed by Fang-** 2020-07-14 19:02 UTC
