### ISSUE TITLE
Error message when trying to create network key/reticket using local Bridge

### ISSUE THREAD

**Issue by mosbuma** [urbit/bridge#386] opened 2020-02-04 08:10 UTC
I am trying to create network keys using a locally installed bridge, but get 

![urbit-networkkeys-error](https://user-images.githubusercontent.com/4919958/73725615-0e2b2e00-472e-11ea-9909-62c417984bb3.png)

Seems like this happens with all operations that interact with Ethereum (create network keys, reticket). 

I am running Bridge bridge-2.3.1 on Ubuntu 16.0.4, using python 3.7.2

**Comment by mosbuma** [comment] 2020-02-04 09:53
After building a local version from source (2.3.3) and connecting to the mainnet I was able to generate the network keys and also able to reticket the planet. Build version 2.3.3 still gives the same error.

**Comment by Fang-** [comment] 2020-02-04 15:52
Huh, so this only happens with the version downloaded from the release page? Very curious, will investigate!

**Comment by mosbuma** [comment] 2020-02-04 16:10
If there is something that I can test/do on my side: just let me know

**Comment by liam-fitzgerald** [comment] 2020-03-12 04:08
potential dupe of #410

**Comment by Fang-** [comment] 2020-07-14 18:36
Indeed. Closing as duplicate of #410.

**Closed by Fang-** 2020-07-14 18:36 UTC
