### ISSUE TITLE
Stage 3 of invite process infrequently renders error on page

### ISSUE THREAD

**Issue by matildepark** [urbit/bridge#329] opened 2019-11-01 05:56 UTC
I've been sending invites and a recipient was unable to finish the invite process. They hit stage 3 on Firefox and supposedly this showed up on the page:

```
fromWei@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:69758
In@https://bridge.urbit.org/static/js/main.eac09ac9.chunk.js:1:123713
Na@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:1561482
Go@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:1604574
Fo@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:1590297
qo@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:1587317
Lo@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:1585877
yi/<@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:1547778
t.unstable_runWithPriority@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:1622221
pi@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:1547507
yi@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:1547724
fi@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:1547659
ko@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:1584868
Ga@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:1564615
852/va</F<@https://bridge.urbit.org/static/js/main.eac09ac9.chunk.js:1:188270
k@https://bridge.urbit.org/static/js/main.eac09ac9.chunk.js:1:62157
c/<@https://bridge.urbit.org/static/js/main.eac09ac9.chunk.js:1:23314
u@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:1762714
l/a._invoke</<@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:1762502
I/</e[t]@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:1763136
r@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:2259
o@https://bridge.urbit.org/static/js/2.3d7a19eb.chunk.js:1:2461
```

They couldn't proceed at all. They had to refresh and sign in from scratch with the master ticket. Presumably they don't have ETH funding. My guess is that we ran out of funds to provide?

**Comment by Fang-** [comment] 2019-11-01 11:05
The gas tank still has plenty of funds. Looking at its recent scrollback, I see one transaction that was ineligible for funding (unlikely to happen during invite flow), and one that was sent as `0x0` (known bug with metamask flow)...

Regardless, I am stumped by this `fromWei` issue. Judging by the hash in filenames here, this is with latest, so no cache issues here. But all our `fromWei` arguments are wrapped in `toBN` as per #321, so those should always render fine... Testing with gas tank failure locally displays the prompt sanely, without crashing.

> They couldn't proceed at all. They had to refresh and sign in from scratch with the master ticket. 

Were they eventually successful? ie, does retrying "fix" this?

**Comment by matildepark** [comment] 2019-11-01 15:50
They didn’t retry the invite flow; they just used the master ticket they received in step 1 and signed into bridge. So. I suppose?

**Comment by Fang-** [comment] 2019-11-01 18:07
Ah, I see. That's very interesting! Moving the point to the new wallet is the final transaction in reticket/invite flows, so _everything succeeded_.

Looking at the code from the stack trace, this does appear to be in the context of a "pls give funds" message... but why would it display that if all transactions seem to have succeeded?

The only thing I can think of is that the gas tank gave an unsatisfactory response, but then went and did funding + transaction submission anyway. Very mysterious.

**Comment by yosoyubik** [comment] 2020-03-26 06:22
An invitee to the pool I'm managing has experienced this (or a similar one) issue at step 3/3 while funding the ethereum transactions.

```
"Your ownership address needs at least 0.01224 ETH and currently has 0 ETH. 
The transaction will automatically resume once enough ETH is available". 
```
I believe that `~litzod` is the sponsor of the pool.

**Comment by Fang-** [comment] 2020-03-26 13:55
@yosoyubik that's intended behavior for when the gas tank cannot fund your transactions for one reason or another. If nobody has ever tried using this invite before, it certainly should be funding though. This is a recent report, right? The only thing that stands out from gas tank logs is a rejection for non-sequential transactions. Strange, because Bridge shouldn't be sending such requests. But if that's your invitee, then they can probably try the invite flow again and it should Just Work?

**Comment by yosoyubik** [comment] 2020-03-26 19:56
@Fang- yes, this happened few days ago. I have forwarded your message :) thanks!

**Comment by Fang-** [comment] 2020-07-14 18:25
This particular error is currently solved as per the workaround in https://github.com/urbit/bridge/issues/410#issuecomment-597855487. Closing.

**Closed by Fang-** 2020-07-14 18:25 UTC
