### ISSUE TITLE
Error Report: Objects are not valid as a React child (found: object with keys {code, message}).

### ISSUE THREAD

**Issue by mcevoypeter** [urbit/bridge#879] opened 2022-01-19 22:26 UTC
## Context

Attempting to sign into Bridge using a Trezor hardware wallet.

## Error

```
_a@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3656012
p@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3658002
y@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3658538
wa/<@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3660820
Rs@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3671928
Qo@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3718103
kl@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703456
Sl@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703384
Il@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703245
hl@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3700211
Hi/<@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3649590
t.unstable_runWithPriority@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3727009
zi@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3649367
Hi@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3649537
Qi@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3649470
dl@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3697580
ks@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3669149
1102/ie/n/<@https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:30441
c@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3735428
u/a._invoke@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3735217
T/</<@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3735853
r@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:45634
l@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:45874

```

In Bridge version 2.10.5.

**Comment by Fang-** [comment] 2022-01-19 23:21
Closing as duplicate of #611, #699 and others. Thanks for filing!

**Closed by Fang-** 2022-01-19 23:21 UTC
Labels: bug, error handling
