### ISSUE TITLE
Unknown "Bridge Error! 🌉🔥" when trying to retrieve XPub

### ISSUE THREAD

**Issue by flips3892** [urbit/bridge#785] opened 2021-11-28 11:52 UTC
**Describe the bug**

When trying to get XPub for the landscape bitcoin client using a ledger the following message is issued.

"We caught an error thrown by the Bridge application client-side code.
Your points and assets are most likely safe.
If you'd like to help us make Bridge better, you can submit the error and your description of events to our GitHub issue tracked"

Are assets at risk? If so which ones and what is the procedure to secure them?  Is it all ETH based assets or just Urbit addresses that can be at risk. 

Also looking for comprehensive instructions on how to get XPub and master ticket and what they are and haven't found them.

**To Reproduce**
Follow the link from the bitcoin client - https://bridge.urbit.org/?kind=xpub

"Step 2 of 2: Import your extended public key
Visit bridge.urbit.org to obtain your key
Extended Public Key (XPub)"

Click acknowledge.  Click metamask, mnemonic, hardware wallet...  

Click Ledger. Etc...

Using a random mnemonic 

**Expected behavior**
Not sure but a vague warning that 'assets' are 'most likely safe' most likely not it.

**Screenshots**

[screen shot](https://i.postimg.cc/9QwMzmDB/error.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox, Chrome, Brave

**Login method (please complete the following information):**
Same when trying to login with mnemonic or ledger.

**Additional context**
Here is the output from the random mnemonic.  Not including the output from the ledger because not sure if it contains private information. The error appeared to be the same in both cases.

If this is a procedure that can put assets at risk, better and clearer instructions and warnings should be a priority.

Bridge Error! 🌉🔥

We caught an error thrown by the Bridge application client-side code.
Your points and assets are most likely safe.

If you'd like to help us make Bridge better, you can submit the error and your description of events to our GitHub issue tracker.

`1102/X<@https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:25699
p/<@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:366802
G/<@https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:25391
1102/zs<@https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:222299
rs@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3663822
Qo@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3716280
kl@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703456
Sl@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703384
Il@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703245
hl@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3700211
Hi/<@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3649590
t.unstable_runWithPriority@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3727009
zi@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3649367
Hi@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3649537
Qi@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3649470
dl@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3697580
ks@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3669149
o/p<@https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:12414
1102/zs</f<@https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:186332
e/<@https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:257764
c@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3735428
u/a._invoke</<@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3735217
T/</<@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3735853
r@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:45634
o@https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:45838
`
You can reload Bridge and retry the operation that caused an error. If the error persists, please submit a bug report and we'll work with you to resolve it!

**Comment by bradyab** [comment] 2022-06-29 15:16
got similar behavior following https://bridge.urbit.org/?kind=xpub in chrome, following metamask workflow, signing with my ledger, then receiving this msg:

```
Error: no urbit wallet found
at Object.Nothing (https://bridge.urbit.org/static/js/main.160ab69c.chunk.js:1:308400)
at b.matchWith (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:495817)
at Object.<anonymous> (https://bridge.urbit.org/static/js/main.160ab69c.chunk.js:1:308092)
at https://bridge.urbit.org/static/js/main.160ab69c.chunk.js:1:279242
at rs (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3249848)
at Qo (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3302306)
at xl (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3289480)
at Sl (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3289408)
at Il (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3289271)
at hl (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3286237)
```

note that I was also unable to import my xPub via master ticket in the bitcoin app in urbit for mac following either workflow. When 1) following the hyperlink to bridge, logging in via master ticket, copying the given Xpub, then pasting it into the dialogue, it hangs. When 2) supplying my master ticket directly in the app, it also hangs:
<img width="413" alt="Screen Shot 2022-06-29 at 10 14 02 AM" src="https://user-images.githubusercontent.com/24712874/176472644-f6956a0c-64d3-4a17-aabb-d2bf6e672d8b.png">

**Comment by Fang-** [comment] 2022-07-27 14:16
Closing as duplicate of #616.

**Closed by Fang-** 2022-07-27 14:16 UTC
