### ISSUE TITLE
Error Report: Object(...)(...) is undefined

### ISSUE THREAD

**Issue by johnmendonca** [urbit/bridge#430] opened 2020-03-25 19:16 UTC
## Context

I logged into bridge using 12-word mnemonic.  This account has one planet which I have not generated keys or done anything else.  I navigated to the admin area where the owner eth address is located.  I clicked copy on the address which worked, and I used it on etherscan on another tab.  When I clicked logout on this screen on bridge I was given the error and prompted to post an issue.

I am using Firefox 74 on MX Linux 18.3 (debian based)
## Error

```
useRouter/data<@https://bridge.urbit.org/static/js/main.21612c58.chunk.js:1194:903
useMemo@https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:159369:9
useMemo@https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:155584:16
useRouter@https://bridge.urbit.org/static/js/main.21612c58.chunk.js:1194:862
Admin@https://bridge.urbit.org/static/js/main.21612c58.chunk.js:2014:1143
dh@https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:159040:7
Jh@https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:159516:7
mj@https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:161789:86
jj@https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160777:13
Z@https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160634:15
$i@https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160493:16
yf/<@https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158219:17
exports.unstable_runWithPriority@https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:162914:12
vf@https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158189:10
yf@https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158214:9
O@https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158204:3
fj@https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160541:23
Sd@https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:157459:7

```

In Bridge version 2.3.5.

**Comment by Fang-** [comment] 2020-03-25 20:00
Might be a duplicate of #403, which has a fix incoming in #406.

**Closed** 2020-06-27 04:10 UTC
