### ISSUE TITLE
Eliminate duplicated points

### ISSUE THREAD

**Issue by arthropodSeven** [urbit/bridge#870] opened 2022-01-09 10:40 UTC
https://github.com/urbit/bridge/blob/0e125345a729dbe64cc1a13216970e05f464e509/src/views/Points.js#L190-L195

Being not very smart, I own a point whose management key is also my address, and it appears twice in this view. 

It could be sufficient to show a visual divider between owned and managed points, but it  might be cleaner to coalesce these into a map based on their ID, and then get that map's values, in order to avoid showing duplicate points.

**Comment by Fang-** [comment] 2022-01-10 20:59
Thanks for filing! This is a duplicate of #526 and I'm closing it as such. This issue may or may not be resolved by the new version of bridge we have in the pipeline.

**Closed by Fang-** 2022-01-10 20:59 UTC
