### ISSUE TITLE
Roller is Offline

### ISSUE THREAD

**Issue by zalberico** [urbit/bridge#1090] opened 2022-12-31 23:43 UTC
The roller we use with bridge appears to be down.

Bridge Login Failure: {"code":7979,"data":{}}

Trying to access bridge via metamask and trezor, but it fails with this error:
<img width="558" alt="Screenshot 2022-12-31 at 3 42 46 PM" src="https://user-images.githubusercontent.com/441466/210157694-e43ca46b-e637-4be7-8a44-760e20bbd7fe.png">

**Comment by zalberico** [comment] 2022-12-31 23:50
Looks like this is a recurrence of https://github.com/urbit/bridge/issues/973 and https://github.com/urbit/bridge/issues/1043

**Comment by zalberico** [comment] 2022-12-31 23:55
<img width="542" alt="Screenshot 2022-12-31 at 3 55 16 PM" src="https://user-images.githubusercontent.com/441466/210157856-6e7bddb7-3262-4325-a396-be002e625fb2.png">

**Comment by zalberico** [comment] 2022-12-31 23:59
This is unrelated to metamask, it doesn't work with master tickets either - looks like something related to the roller.

**Comment by zalberico** [comment] 2023-01-01 00:02
It may need to be restarted after I updated it to 1.15? https://developers.urbit.org/reference/azimuth/l2/roller-tutorial

**Comment by zalberico** [comment] 2023-01-01 00:30
@yosoyubik putting this on your radar, I took a look but we don't have much internal docs about our roller (something we should change).

I'm not sure if what I did earlier today caused this or if it was already broken.

I did the following this morning:
 - Updated the binary on the roller moon to 1.15 (shut it down to do this and docked it)
 - Deleted other directories on the box that were not the moon (cleaned up old binaries, I don't think anything there was important, but it's possible I'm wrong)
 - Created a backup checkpoint in .urb
 - Ran |pack
 - Started the moon back up.

I did a similar workflow on every infra urbit we host. The only thing I did differently for the roller was I didn't delete the caddy file in the home directory because I wasn't sure if it was important.

**Comment by zalberico** [comment] 2023-01-01 00:32
@tomholford - I know you also know a lot about bridge so tagging you on this too for context.

**Comment by yosoyubik** [comment] 2023-01-01 10:07
@zalberico it should work now—I tested it running `curl`.

<details>

<summary>e.g.</summary>

```
curl -k --location --request POST 'https://roller.urbit.org/v1/roller' \                                                                                                  
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "getPoint",
    "params": {
        "ship": "~norsyr-torryn"
    },
    "id": "1234"
}' | jq

```
</details>

The issue was that the new binary was not allowed to run on port 80, so it was running on 8080 upon restart, so doing:

 `sudo setcap 'cap_net_bind_service=+ep' ./roller-dozzod-dozzod/.run` 

fixed it. We were running a custom binary for the roller, to prioritize HTTP requests. I can't find if there was an issue about that—probably it was just discussed internally—or a branch with the changes for the interpreter (@philipcmonk do you remember if we had those changes somewhere?).

**Comment by zalberico** [comment] 2023-01-01 23:50
Thanks - is that caddyfile in the urb home directory used for anything?

**Comment by yosoyubik** [comment] 2023-01-02 04:46
We don't use it anymore (I just removed it)—we use %acme now to enable SSL.

**Comment by tomholford** [comment] 2023-01-04 00:14
Closing since this is now working as expected (thanks @yosoyubik !)

**Closed by tomholford** 2023-01-04 00:14 UTC

**Comment by zalberico** [comment] 2023-01-04 00:24
What about the custom binary @tomholford? Does that matter?

**Comment by tomholford** [comment] 2023-01-04 00:27
> What about the custom binary @tomholford? Does that matter?

IIRC, this was a temporary bandaid to handle excessive load from the Bridge frontend. There was a bug that was DDOSing the roller. We eventually found the root cause and fixed it, so the custom binary is no longer necessary.
