### ISSUE TITLE
Error Report: no urbit wallet found

### ISSUE THREAD

**Issue by marcoleder** [urbit/bridge#1018] opened 2022-04-21 13:35 UTC
Hey there :) 

I wanted to set up a bitcoin wallet for ~ticsun-rigpen, however, I encountered an error. The planet is on L2, was originally a master ticket (paper wallet) but I transferred ownership and management to my hardware wallet address 0x8501b249B3aC9FD252fCA8B131410832a3190ec4

When trying to get the xpub-key via metamask extension, the following error shows:

```
Error: no urbit wallet found
    at Object.Nothing (https://bridge.urbit.org/static/js/main.160ab69c.chunk.js:1:308400)
    at b.matchWith (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:495817)
    at Object.<anonymous> (https://bridge.urbit.org/static/js/main.160ab69c.chunk.js:1:308092)
    at https://bridge.urbit.org/static/js/main.160ab69c.chunk.js:1:279242
    at rs (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3249848)
    at Qo (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3302306)
    at xl (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3289480)
    at Sl (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3289408)
    at Il (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3289271)
    at hl (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3286237)
```

In Bridge version 3.1.0.

But when I use my master ticket to import the xpub then no error shows. May I ask if importing via master ticket and logging in via bridge has the same outcome/result? 

Can I withdraw funds of the bitcoin wallet, even if I cannot log in with my master ticket (since it's not the owner anymore)?

Best regards
Marco Leder

**Comment by Fang-** [comment] 2022-04-28 13:47
Yes, as per similar issues, the Bitcoin wallet in Bridge is not supported for non-master-ticket logins.

If you log in with your old master ticket (you should be able to click "log in anyway") you'll be able to derive the same old xpub, and sign transactions using the same old key. In other words, your old login details still let you access the same Bitcoin wallet.

**Comment by bradyab** [comment] 2022-06-29 15:20
related: https://github.com/urbit/bridge/issues/785#issuecomment-1170110135

**Comment by Fang-** [comment] 2022-07-27 14:16
Closing as duplicate of #616.

**Closed by Fang-** 2022-07-27 14:16 UTC
Labels: bug, hw wallets
