### ISSUE TITLE
Gank tank failed on setting management address

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#263] opened 2019-08-29 21:04 UTC
![setting-mgmt-address](https://user-images.githubusercontent.com/9557907/63976292-dbd22200-ca65-11e9-8151-5006bab4e5a7.gif)
Is this expected behavior?

**Comment by Fang-** [comment] 2019-08-29 21:40
(Please include a still of the console output next time. (; )

"please pass numbers" damnit, how many times do we have to fix this?

But also, "request rejected"? Huh. Did you run this against a local gas tank, or a real one?

**Comment by Fang-** [comment] 2019-08-29 21:59
Just reproduced on testnet. Console says it got rejected, but it sent funds anyway? Investigating!

**Comment by jyng** [comment] 2019-08-29 22:54
> (Please include a still of the console output next time. (; )
What do you mean by this?

**Comment by Fang-** [comment] 2019-08-29 22:57
> How would I achieve that?

<img width="289" alt="image" src="https://user-images.githubusercontent.com/3829764/63981866-02717680-cac1-11e9-900c-15e6b8959d54.png">

**Comment by Fang-** [comment] 2019-08-29 23:14
Wait, actually, let's not forget that we only fund up to six transaction for every point. You may have already gone over your limit. All other rejection cases have printfs in the gas tank itself, and I see no output there.

Go find a Ropsten ETH faucet and get yourself some! (Metamask has one, and I have some on hand if you can give me your address.) Alternatively, I can reset the state of the testnet gas tank, I guess.

The "please pass numbers" one is still an error though!

**Comment by Fang-** [comment] 2019-08-29 23:23
Uh oh, looks like I had neglected to update the hosted testnet version. Latest should be on there now, which should have this behave sanely. Look for version `r-190827-1`.

Closing under the assumption that this is already resolved!

**Closed by Fang-** 2019-08-29 23:23 UTC

**Comment by jyng** [comment] 2019-08-30 21:03
Ok I'll try loading with Ropsten and respond accordingly

**Comment by jyng** [comment] 2019-08-30 21:26
Yep successful
