### ISSUE TITLE
Bridge falsely claims MetaMask wallet doesn't contain an azimuth point

### ISSUE THREAD

**Issue by bendini** [urbit/bridge#545] opened 2021-01-14 21:55 UTC
I have a wallet that contains an azimuth point but when I log I get the warning message "This wallet is not the owner or transfer proxy for this point." and when I press Login Anyway I get "No points to display. This wallet is not the owner or proxy for any points."

My MetaMask wallet shows the point in addition to etherscan https://etherscan.io/tx/0x092456cb15f6d19f12d8a0c60fb5ad3da9a9b35f6893a5cb2c859e051e48dc51

**Comment by Fang-** [comment] 2021-01-14 22:13
Hmm, I can reproduce this for other addresses as well. Looks like something got seriously broken with recent changes. Investigating, thank you!

**Comment by Fang-** [comment] 2021-01-14 22:48
Actually, my reproduction was due to something dumb along the lines of connecting to the wrong network. With that fixed, can no longer reproduce.

@bendini, just in case, can you confirm that your Metamask was/is pointing at mainnet, and not some testnet or other non-mainnet node?

**Comment by bendini** [comment] 2021-01-14 23:06
Yes, I can confirm it is pointing at mainnet

**Comment by Fang-** [comment] 2021-01-14 23:11
Good, thanks. One more question: after you log in, on the "no points to display" screen, it shows the address `0xb59a4add88df948c68872c040d818a77dc7d0ee3` in the top left, correct?

**Comment by bendini** [comment] 2021-01-14 23:20
No, it shows 0x6cE4E9F077DAc04276488C332760fafACF6c51a2

**Comment by bendini** [comment] 2021-01-14 23:23
I'd like to add add that I do not control a metamask wallet with that address, so I have no idea where it came from.

**Comment by Fang-** [comment] 2021-01-14 23:24
That address doesn't own any points, and doesn't have control at all over the point transferred in the transaction you linked. The address I posted owns that point, so you'll need to log in with that to manage it in Bridge. Are you maybe logging in with a different account?

**Comment by bendini** [comment] 2021-01-14 23:30
I've tried logging in using MetaMask in a different browser, it's still the same and I have no idea what account that belongs to.

**Comment by bendini** [comment] 2021-01-14 23:34
update: I selected the option to login specifically with MetaMask and it now works.

**Comment by Fang-** [comment] 2021-01-14 23:34
Oh, wow, now I'm wondering what login method you were using before!

Closing, in any case. Glad to hear you got in. (:

**Closed by Fang-** 2021-01-14 23:34 UTC

**Comment by bendini** [comment] 2021-01-14 23:41
the default one that is presented to the user, where it asks for the urbit planet id and the master ticket
