### ISSUE TITLE
No keyfile included when downloading master ticket

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/bridge#1023] opened 2022-05-28 16:45 UTC
https://twitter.com/SadeBaeza/status/1530376196931739648?s=20&t=9mT0JDpbopJRySmTj-Wr_w

**Comment by tacryt-socryp** [comment] 2022-07-14 17:58
Hi there, this issue is still live. What's the deal here?

**Comment by zalberico** [comment] 2022-07-14 20:28
Closing as duplicate of https://github.com/urbit/bridge/issues/1010

**Closed by zalberico** 2022-07-14 20:28 UTC
Labels: bug
