### ISSUE TITLE
Transaction Broadcasts to Ethereum Failing

### ISSUE THREAD

**Issue by bioy-casares** [urbit/bridge#292] opened 2019-09-25 19:55 UTC
For point transfers and retickets, >50% of attempts to "Send Transaction" yields following error.  Button reverts to "Reset Transaction"

<img width="1440" alt="Screen Shot 2019-09-25 at 12 52 27 PM" src="https://user-images.githubusercontent.com/55156412/65634635-8705c680-df93-11e9-8501-55fde9cdba1f.png">

**Comment by vvisigoth** [comment] 2019-09-25 22:15
Huh. I've never seen that error before (replacement transaction underpriced). Was this done on the same address as #291 ?

cc @Fang-

**Comment by Fang-** [comment] 2019-09-26 12:13
This indicates you still have a "pending" transaction out on the Ethereum network. Bridge should always wait for transactions to resolve before it lets you continue, preventing you from running into situations like this. Can you describe what you were doing leading up to this?

**Comment by bioy-casares** [comment] 2019-09-26 18:31
@vvisigoth No, I believe this was a different address than issue #291.  

@Fang I was accepting several planet transfers, then transferring them to a different Ethereum address.   As the accepts and transfers were frequently failing, I was trying different browsers, trying different planets.  It's possible that I previously failed to accept the transfer for this planet when I took this screenshot. 

I since realized that the Gas Rate could be changed under the Advanced setting.  After doing this, it resolved many of these issues.  @eriknewton and I agreed that we should up the base gas rate.

**Comment by Fang-** [comment] 2019-09-26 18:56
> I was trying different browsers, trying different planets

Seems like the cause of this issue. Bridge works fine if you have a single instance open and go through the flows at the pace it sets. It's highly impractical to try and support the "doing multiple things from multiple places with the same account at once" case. (Because of how Ethereum works/how we need to build transactions.)

Setting a higher gas price (at least 10% higher than the still-pending transaction's price) allows you to override the still-pending transaction and force your way through this error (ie successfully replace the tx). But that's all outside of the normal, expected flow, for which the auto-selected gas price is fine.

Closing this for now as """not an issue""", since we don't intend to support usage flows outside of Bridge's (admittedly flimsy) guard rails. @bioy-casares if any of the above seems inaccurate/doesn't capture your issue, feel free to object, and we can re-open as needed.

**Closed by Fang-** 2019-09-26 18:56 UTC
