### ISSUE TITLE
Arvo keyfile fails to generate for non-Urbit Wallet users

### ISSUE THREAD

**Issue by msutherl** [urbit/bridge#145] opened 2019-06-07 21:11 UTC
Some recent issues reported to support@urbit.org:

User 1

> I used bridge to unlock my wallet using the master ticket, I then clicked on 'set public keys', it didnt work the first time but it worked the second time. I can see them on the bottom of my point page. I then clicked on 'generate arvo keyfile' which was generated and downloaded to my computer.

User 2

> I am unable to download the keyfile for my planets. I booted Bridge, logged in with my ethereum private key, and clicked "Set public keys". When doing so, I was given the following warning:
>
> The process appears to have been successful though, because the "Public Keys" section, which previously had been empty, now has data in it.
>
> But when I click "Generate Arvo keyfile", I get the following:
> 
> <img width="402" alt="5E1DBBEE-A51B-4401-824E-F472DF41FCF0" src="https://user-images.githubusercontent.com/31774/59137440-be952800-893c-11e9-8408-500cbe5bdd54.png">
>
> I do not see any link to reset my networking keys. The docs at https://urbit.org/docs/getting-started/using-bridge/ suggest there should be such a link. Not sure if it's out of date or whether I'm just not seeing it. I never had to go through the "Accept Your Transfer" process though (to the best of my recollection) as these planets pre-date Azimuth.

User 3

> I'm finally getting to boot my planet up and running into some confusion about proper Bridge usage to fully get on the network. 
>
> I've entered my private key (for my ethereum address) and can see my planet. But initially I wasn't given the option to accept transfer, so I added some eth to this address and went about setting up my public keys. 
>
> Once issued, I'm now in a confusing configuration. I can't accept the incoming transfer, or generate my Arvo keyfile. 

My best guess is that in each of these cases, they're trying to generate the Arvo keyfile before the "Set public keys" transaction completes, but I'm waiting for confirmation about that. Could be interesting to try to reproduce.

**Comment by Fang-** [comment] 2019-06-07 21:20
Thanks for filing these!

> My best guess is that in each of these cases, they're trying to generate the Arvo keyfile before the "Set public keys" transaction completes

That sounds right for user 1, but idk about the others.

Users 2 and 3 talk abut the "accept your transfer" part of the flow. Docs needs to be clarified that you only need to do this if someone spawned/sent you a planet. People who got their planets from us directly (either during 2019-01 launch or any we've been sending later) don't need to "accept transfer" at all!

Would be useful to know the point number of user 3, knowing the chain state would help figure out/reproduce this. A screenshot of their point overview/actions page would also be helpful, I'm not sure what exactly their "confusing configuration" looks like.

**Comment by msutherl** [comment] 2019-06-07 22:58
@Fang- added relevant image, and both users 2 and 3 mention not being able to generate Arvo keyfile

**Comment by Duncanswilson** [comment] 2019-06-09 00:54
I was user 3, I got it sorted by re-generating my public keys and now I was able to download my Arvo keyfile.

**Comment by msutherl** [comment] 2019-06-10 22:34
User 3 has been doxed! I guess this is as expected – the UI doesn't clearly indicate that you need to wait for the transaction to go through, and should really be smart enough to guide you through this.

**Comment by Fang-** [comment] 2019-06-20 15:30
Closing this as not a Bridge issue. Keyfile generation for random keys (ie when not using an Urbit HD Wallet) works fine if you do it within the same session as setting keys, which it warns you to do.

**Closed by Fang-** 2019-06-20 15:30 UTC
