### ISSUE TITLE
Bridge seems to calculate price gas incorrectly

### ISSUE THREAD

**Issue by ynx0** [urbit/bridge#555] opened 2021-02-23 10:13 UTC
I tried signing and sending a transaction through bridge and kept the default gas setting.
However, the trans

I've narrowed it down to here, where apparently the gas prices are being taken from https://ethgasstation.info
https://github.com/urbit/bridge/blob/a2dd484e3a5f0f1a24e51bd80c5c1077a3b03f1c/src/lib/getSuggestedGasPrice.js#L13-L19

However, at the time of writing, ETH Gas Station shows incorrectly low gas prices for some reason.

See:
![Screenshot from 2021-02-23 05-10-02](https://user-images.githubusercontent.com/9275716/108828886-70530d00-7595-11eb-8e7f-d94c92f3c135.png)
which shows 10 gwei for all categories.

While https://etherscan.io/gastracker
![image](https://user-images.githubusercontent.com/9275716/108828943-8234b000-7595-11eb-8adb-ddf71dd9c80a.png)
shows 635 gwei for the lowest price (!).

Edit: yet another source (https://ethereumprice.org/gas/) shows 10 gwei as well, so honestly idk what's going on
![image](https://user-images.githubusercontent.com/9275716/108831617-5f57cb00-7598-11eb-8a1e-8a982e347028.png)

**Comment by Fang-** [comment] 2021-03-01 14:36
Hmm. I don't think Bridge can know if the result it gets from ethgasstation is "correct" or not. We could check with multiple such services and take an average, but that's still subject to this issue. Might consider this Not A Bug...

**Comment by ynx0** [comment] 2021-03-01 20:19
I know what you mean, but imo if there's still no indication to the user that the transaction timed out then the *default* user flow has a chance of failing randomly. Even with this indication, it will waste a bit of the user's gas and time, and then force them to check the gas prices to figure out that bridge just underestimated it. I think either (a) picking a more reliable source or (b) cross-referencing multiple sources and picking the ones which agree would solve it like you said. I'm happy to take a crack at the implementation of whatever you'd like done.

**Comment by Fang-** [comment] 2021-03-04 18:55
> I'm happy to take a crack at the implementation of whatever you end up choosing.

That'd be amazing! If you can pitch me a known-reliable alternative, I'd be happy to review/approve a switch to it. It's not obvious to me that "picking the ones which agree" is feasible, considering different providers can't guarantee they use the same heuristics, but if I'm wrong I'd love to hear it.

**Comment by ynx0** [comment] 2021-03-07 16:51
I did some research and thought of two techniques:
- cross-check multiple sources for agreement on current gas prices
- check historical trends (using one source for simplicity) to see if there is high motion/volatility in the gas prices

Recommendation: 
(a) check for anomalous gas price reports and discard them and 
(b) average gas prices between sources or just pick one that is close enough to mean. 

More specifically, we can choose a given gas price report as the base to compare to, then check how far off each other source is. If most of the differences between the base and other sources are under a certain threshold, we simply discard the reading that is over the threshold and use the ones that agree. Alternatively we could use something like standard deviation to remove outliers, then take the average.

This however, doesn't uncompromisingly protect us from weird API outages, miscalculations, or weird gas prices happenings. The general solution imo is to surface to the user information that something is going wrong with gas prices: whether it be true volatility or confusion between different gas API sources, both represent uncertainty that is hard to deal with in a nice and sealed fashion on the system's end. So, we inform the user precisely of this uncertainty.

This does two things: 
(a) it removes the burden of creating a *100% infallible/known-reliable* gas price estimating system, and 
(b) actually gives the user enough information to then have them be able to do something about it (i.e. research the gas price on their own, cross-check, etc), and still allows them to make the final decision where we (the system) can no longer help. 

A simple message such as,
- "Warning: gas prices seem to be experiencing high volatility. Please choose the gas price with more caution, and be aware that the transaction could have a higher likelihood of failing.", or
- "Warning: various gas price reports seem to disagree."

for these types of failure modes could go a long way.


<details>
<summary>
	Research
</summary>


### Default Solution
web3.estimateGas

[How do I know how much gas to use when calling a contract?](https://ethereum.stackexchange.com/questions/197/how-do-i-know-how-much-gas-to-use-when-calling-a-contract/209#209)

It's pitfalls

[What are the limitations to estimateGas and when would its estimate be considerably wrong?](https://ethereum.stackexchange.com/questions/266/what-are-the-limitations-to-estimategas-and-when-would-its-estimate-be-considera/515#515)

It seems like this is a hard problem that you can't really "solve" once and for all.


### Etherscan Stuff
https://etherscan.io/apis#gastracker

- Get Estimation of Confirmation Time - https://api.etherscan.io/api?module=gastracker&action=gasestimate&gasprice=2000000000&apikey=YourApiKeyToken
	- (Result returned in seconds, gasprice value in Wei)
- Get Gas Oracle - https://api.etherscan.io/api?module=gastracker&action=gasoracle&apikey=YourApiKeyToken
	- (SafeGasPrice, ProposeGasPrice And FastGasPrice returned in Gwei)


### Gas Now

https://www.gasnow.org/
https://taichi.network/#gasnow
https://decrypt.co/43046/gasnow-the-hot-new-tool-that-predicts-ethereum-gas-prices

https://www.gasnow.org/api/v3/block/history
https://www.gasnow.org/api/v3/gas/price?utm_source=web (we care about this one, reports rapid/fast/regular/slow in wei)

Apparently straight from a mining pool.

From their website, this is how they predict prices:

Queue
    Pending transaction queue Q: [TX1,TX2,TX3…TX N…TX2000], sorted by gas price (from highest to lowest)
    Mining queue: [TX1,TX2,TX3…TX N], length: N
    Avg. block time: 13.5s. Avg. txs in a block: 200

GasPrice
    Rapid: the median of Gas Prices of transactions in the mining block
    Fast: the Gas Price of TX N, which is the minimum in the mining block
    Standard: the Gas Price of the Max(2N, 500) th transaction in Q
    Slow: the Gas Price of the Max(5N, 1000) th transaction in Q




### Aggregator: EthGasWatch

https://ethgas.watch/api/gas
not reliable/i wouldn't trust in long term, but we could basically copy what they are doing and use whatever sources they have

example gas data

```
{
	"slow": {
		"gwei": 123,
		"usd": 4.26
	},
	"normal": {
		"gwei": 134,
		"usd": 4.64
	},
	"fast": {
		"gwei": 139,
		"usd": 4.82
	},
	"instant": {
		"gwei": 146,
		"usd": 5.06
	},
	"ethPrice": 1649.82,
	"lastUpdated": 1615129261223,
	"sources": [{
		"name": "Etherscan",
		"source": "https://etherscan.io/gastracker",
		"fast": 156,
		"standard": 143,
		"slow": 123,
		"lastBlock": 11992053
	}, {
		"name": "Etherchain",
		"source": "https://etherchain.org/tools/gasPriceOracle",
		"instant": 146,
		"fast": 139,
		"standard": 134,
		"slow": 123,
		"lastUpdate": 1615129260131
	}, {
		"name": "Gas station",
		"source": "https://ethgasstation.info/",
		"instant": 143,
		"fast": 139,
		"standard": 133,
		"slow": 124,
		"lastBlock": 11992053
	}, {
		"name": "GAS Now",
		"source": "https://www.gasnow.org/",
		"instant": 150,
		"fast": 132,
		"standard": 119,
		"slow": 110,
		"lastUpdate": 1615129254515
	}, {
		"name": "MyCrypto",
		"source": "https://gas.mycryptoapi.com/",
		"instant": 145,
		"fast": 138,
		"standard": 134,
		"slow": 123,
		"lastBlock": 11992054
	}, {
		"name": "POA Network",
		"source": "https://gasprice.poa.network/",
		"instant": 146,
		"fast": 139,
		"standard": 134,
		"slow": 125,
		"lastBlock": 11992056
	}, {
		"name": "Upvest",
		"source": "https://doc.upvest.co/reference#ethereum-fees",
		"instant": 175,
		"fast": 165,
		"standard": 139,
		"slow": 114,
		"lastUpdate": 1615129261222
	}]
}
```


Also has a trend api, which we could use to calculate anomalies.
https://ethgas.watch/api/gas/trend

</details>

**Comment by Fang-** [comment] 2021-03-08 20:03
Thanks @ynx0, this is very thorough!

> I'm mainly just advocating for surfacing gas price uncertainty to the user in some form to allow them to make their own decision.

Bridge has traditionally held a very "hide the Ethereum from the user" stance when it comes to these things. Surface if the user opts into it, but hide all the blockchain nonsense otherwise. This hasn't always been great at reducing confusion ("why is this progress bar stuck?"), and complicates things when we do have to let the underlying technology shine through.

I'm gonna tag in @jyng and @urcades here, to consider this for the one-of-these-days Bridge redesign/tweaks, and answer this question: what can we do about this in the short term? Maybe we're fine just putting a little bit of text underneath the "sign transaction" button in such conditions, but how will that look to users who don't know what a gas is?

**Comment by Fang-** [comment] 2021-08-24 19:52
Looking at ethgasstation.info again, now it's giving way higher gas prices compared to Etherscan. The former is saying 400+ gwei for a fast transaction, the latter only 70+.

Might not be too hard to straight-up swap it out for the Etherscan API. That generally seems a lot more reliable. The above would still be good but is a somewhat more expensive change.

**Comment by lukestiles** [comment] 2022-07-25 22:44
Closing as fixed based on the PR and L2

**Closed by lukestiles** 2022-07-25 22:44 UTC
Labels: feature, interface
