### ISSUE TITLE
`npm run release` does not work without some additional packages installed

### ISSUE THREAD

**Issue by dpc** [urbit/bridge#16] opened 2019-01-19 05:01 UTC
```
npm install azimuth-solidity
npm install sigil-js
```

I'm guessing they have to added to `package.json`?

**Comment by jtobin** [comment] 2019-01-19 07:34
@dpc I can't reproduce, but both of these are already in `package.json`.  Will close this one.

**Closed by jtobin** 2019-01-19 07:34 UTC
