### ISSUE TITLE
Error Report: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bticket%2C%20signedTx%2C%20rawTx%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

### ISSUE THREAD

**Issue by snus-kin** [urbit/bridge#471] opened 2020-06-02 15:41 UTC
## Error

```
mg@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158653:38
z@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158747:9
rb@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158813:13
ng/<@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158930:23
S@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:159502:26
mj@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:161843:306
jj@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:160809:13
Z@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:160666:15
$i@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:160525:16
yf/<@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158251:17
exports.unstable_runWithPriority@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:162946:12
vf@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158221:10
yf@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158246:9
O@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158236:3
eg@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:160481:48
sh@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:159297:7
useFormState/</<@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:24458:17
memoize/<@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:25176:23
notifySubscriber@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:25247:15
notify/<@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:25264:27
notify@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:25256:24
notifyFormListeners@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:25686:17
complete@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:26114:9

```

In Bridge version 2.5.0.

**Comment by Fang-** [comment] 2020-06-02 18:34
Closing as duplicate of #455. Good to know this is still a problem on latest though, thanks for reporting!

**Closed by Fang-** 2020-06-02 18:34 UTC
