### ISSUE TITLE
UI bugs when using mnemonic option for generating an urbit keyfile

### ISSUE THREAD

**Issue by zaphar** [urbit/bridge#71] opened 2019-03-08 15:15 UTC
When trying to boot up fosnut-dandut on the new network I ran into an issue with the bridge tool when using the Mnemonic option.

After entering the mnemonic and getting access to the point in the Bridge UI I navigated to the generate a Keyfile page and the seed box was empty. I generated a random seed to enter into the box and it turned green. However clicking the generate button had no effect. No key was generated and no option to download the file appeared.

This was repeatable  even after restarting the bridge server and clearing all browser data.

Starting over with the master ticket instead of the mnemonic worked as expected.

**Comment by Fang-** [comment] 2019-03-08 15:48
Reading this here, I think this is a duplicate of both #57 and #65.

Keyfile download should "just like work" at the click of a button for master ticket and management mnemonic login, confusing input fields be damned.

**Comment by c-johnson** [comment] 2019-04-11 00:00
Fixed via https://github.com/urbit/bridge/pull/85. Let us know if you have any more issues with this.

**Closed by c-johnson** 2019-04-11 00:00 UTC
