### ISSUE TITLE
Error Report: pattern[name] is not a function

### ISSUE THREAD

**Issue by mcouthon** [urbit/bridge#447] opened 2020-04-13 20:06 UTC
## Context

Pressed "back" after creating network keys.

## Error

```
TypeError: pattern[name] is not a function
    at InternalConstructor.matchWith (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:61028:29)
    at Object.Just (https://bridge.urbit.org/static/js/main.21612c58.chunk.js:1744:2465)
    at InternalConstructor.matchWith (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:61028:29)
    at renderNetworkKeysDetail (https://bridge.urbit.org/static/js/main.21612c58.chunk.js:1744:2338)
    at AdminEditPermissions (https://bridge.urbit.org/static/js/main.21612c58.chunk.js:1744:3433)
    at dh (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:159040:7)
    at mj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:161732:11)
    at jj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160777:11)
    at Z (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160634:15)
    at $i (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160493:16)
```

In Bridge version 2.3.5.

**Comment by Fang-** [comment] 2020-06-05 14:27
Closing as duplicate of #332. Thanks for reporting, the context here is helpful!

**Closed by Fang-** 2020-06-05 14:27 UTC
