### ISSUE TITLE
Error Report: sigil.js cannot render @p of length 8. Only lengths of 1 (galaxy), 2 (star), and 4 (planet) are supported at this time.

### ISSUE THREAD

**Issue by vshvedov** [urbit/bridge#480] opened 2020-06-26 21:05 UTC
## Error

```
construct@[native code]
_construct@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:236630:26
Wrapper@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:92325:23
ConfigError@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:56227:79
sigil@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:56300:26
dh@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:159072:8
mj@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:161764:13
jj@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:160809:13
Z@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:160666:17
Z@[native code]
$i@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:160525:17
$i@[native code]
https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158251:18
https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:162946:13
yf@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158246:9
O@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158236:5
fj@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:160573:24
Sd@https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:157491:7
Sd@[native code]
```

In Bridge version 2.5.0.

**Comment by Fang-** [comment] 2020-07-14 21:29
Closing as duplicate of #344.

**Closed by Fang-** 2020-07-14 21:29 UTC
