### ISSUE TITLE
WalletMiddleware - Invalid "from" address.

### ISSUE THREAD

**Issue by ixv** [urbit/bridge#449] opened 2020-04-21 18:26 UTC
I'm trying to reset the networking keys for a ship that I do not have the master key for, only the management proxy. I'm using metamask for this. I get this error:

![image](https://user-images.githubusercontent.com/4741759/79900033-751dc200-83c2-11ea-851a-e43efd269550.png)

here is my console:

![image](https://user-images.githubusercontent.com/4741759/79900247-cc239700-83c2-11ea-9263-51174e580f98.png)

**Comment by Fang-** [comment] 2020-04-21 19:43
@ixv you use Brave, right? This might be related: https://github.com/urbit/bridge/issues/421#issuecomment-600946879

**Comment by Fang-** [comment] 2020-07-14 18:53
Closing as duplicate of #421.

**Closed by Fang-** 2020-07-14 18:53 UTC
