### ISSUE TITLE
Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE

### ISSUE THREAD

**Issue by urcades** [urbit/bridge#623] opened 2021-09-03 21:00 UTC
I'm receiving the above error when trying to authenticate into bridge with my Ledger wallet, which is up to date and otherwise able to access Ledger's own app, etc.

**Comment by Fang-** [comment] 2021-09-04 14:17
Yes there's issues with Ledger in Chrome. Using either Firefox, or hooking your Ledger up to Metamask, should let you work around this for now.

Unless you're seeing this despite using a workaround, this can be closed as duplicate of #581.

**Comment by lukestiles** [comment] 2022-07-25 22:57
Closed as duplicate.

**Closed by lukestiles** 2022-07-25 22:57 UTC
Labels: bug, hw wallets
