### ISSUE TITLE
Error Report: Cannot create property 'message' on string 'Node error: {"code":-32000,"message":"already known"}'

### ISSUE THREAD

**Issue by sphinxx0000** [urbit/bridge#481] opened 2020-06-26 22:51 UTC
I was trying to claim a planet sent to me by Tlon support team. Going to try again. Working from Chrome on Mac OS

## Error

```
TypeError: Cannot create property 'message' on string 'Node error: {"code":-32000,"message":"already known"}'
    at renderAdditionalInfo (https://bridge.urbit.org/static/js/main.b6a701ac.chunk.js:2322:385)
    at PassportTransfer (https://bridge.urbit.org/static/js/main.b6a701ac.chunk.js:2322:1914)
    at dh (https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:159072:7)
    at Jh (https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:159548:7)
    at mj (https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:161821:86)
    at jj (https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:160809:11)
    at Z (https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:160666:15)
    at $i (https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:160525:16)
    at https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:158251:17
    at push.exports.unstable_runWithPriority (https://bridge.urbit.org/static/js/2.a3f8391b.chunk.js:162946:12)
```

In Bridge version 2.5.0.

**Comment by vvisigoth** [comment] 2020-06-26 22:53
@Fang- have you seen this before?

**Comment by Fang-** [comment] 2020-06-26 22:56
Looks like it was trying to show an error message and errored out while doing so.

"already known" suggests the transaction(s) succeeded though. We try to catch these, since they're generally a harmless side-effect of helping you pay for the transaction. I wonder why this thought it was an actual error...

> Going to try again.

If your invite no longer works, you can probably log in with the master ticket that you downloaded.

**Comment by Fang-** [comment] 2020-07-14 21:30
Closing as duplicate of #478. Thanks for filing!

**Closed by Fang-** 2020-07-14 21:30 UTC
