### ISSUE TITLE
Error Report: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bticket%2C%20signedTx%2C%20rawTx%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### ISSUE THREAD

**Issue by sapset-fansyx** [urbit/bridge#504] opened 2020-07-19 01:27 UTC
## Context

I was trying to invite people to my Planet. I put in their email addresses; I got this error.  Edit: it does say "pending" now though. 

## Error

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bticket%2C%20signedTx%2C%20rawTx%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Qg (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:174063:36)
    at p (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:174153:7)
    at ca (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:174218:37)
    at https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:174342:23
    at R (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:175048:26)
    at Rj (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:177461:306)
    at Qj (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:176905:11)
    at Kj (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:176897:27)
    at yj (https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:176640:7)
    at https://bridge.urbit.org/static/js/2.dc5800ce.chunk.js:173675:18
```

In Bridge version 2.5.3.

**Comment by risruc-habteb** [comment] 2020-07-19 19:10
Same issue/error trying to send planet invites by email.

**Comment by Fang-** [comment] 2020-07-20 14:33
Closing as duplicate of #455. Will have a fix for that soon, thanks for reporting!

**Closed** 2020-07-20 16:47 UTC
