### ISSUE TITLE
"Copy" for Login Code doesn't work

### ISSUE THREAD

**Issue by rmariani** [urbit/bridge#489] opened 2020-07-14 00:39 UTC
Pressing "copy" doesn't update the information on the clipboard. `ctrl-v`ing doesn't paste the code. I've tried on two different machines on two different browsers (Firefox and Chrome).

**Comment by Fang-** [comment] 2020-07-14 21:33
Closing as duplicate of #472.

**Closed by Fang-** 2020-07-14 21:33 UTC
