### ISSUE TITLE
Error Report: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bticket%2C%20signedTx%2C%20rawTx%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

### ISSUE THREAD

**Issue by Kwaskoff** [urbit/bridge#464] opened 2020-05-15 07:17 UTC
## Error

```
mg@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:158624:38
z@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:158718:9
rb@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:158784:13
ng/<@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:158901:23
S@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:159473:26
mj@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:161814:306
jj@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:160780:13
Z@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:160637:15
$i@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:160496:16
yf/<@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:158222:17
exports.unstable_runWithPriority@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:162917:12
vf@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:158192:10
yf@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:158217:9
O@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:158207:3
eg@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:160452:48
sh@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:159268:7
_callee$@https://bridge.urbit.org/static/js/main.57d78efe.chunk.js:2342:947
tryCatch@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:164063:17
invoke@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:164282:30
defineIteratorMethods/</prototype[method]@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:164116:21
asyncGeneratorStep@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:213:24
_next@https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:235:27

```

In Bridge version 2.4.1.

**Comment by sxiii** [comment] 2020-05-15 07:21
Duplicate of #455

**Comment by Fang-** [comment] 2020-06-02 18:33
Closing as duplicate of #455. Thanks for reporting regardless!

**Closed by Fang-** 2020-06-02 18:33 UTC
